name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'azul'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: run test
      run: ./gradlew test

    - name: run build
      run: ./gradlew clean build -x test
