name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'zulu' # See 'Supported distributions' for available options
       cache: 'gradle'
    - run: ./gradlew build --no-daemon
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: run test
      run: ./gradlew test

    - name: run build
      run: ./gradlew clean build -x test
